'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const generator = require('../scripts/generate-setup-question-docs.cjs');

function temporaryOutput(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'toolkit-setup-question-docs-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  return path.join(root, 'SETUP-QUESTIONS.generated.md');
}

test('setup question freshness accepts canonical LF and CRLF but rejects real drift', (t) => {
  const target = temporaryOutput(t);
  const expected = generator.generatedBytes();

  fs.writeFileSync(target, expected, 'utf8');
  assert.doesNotThrow(() => generator.checkGeneratedDocument(target));

  fs.writeFileSync(target, expected.replace(/\n/g, '\r\n'), 'utf8');
  assert.doesNotThrow(() => generator.checkGeneratedDocument(target));

  const firstLineFeed = expected.indexOf('\n');
  assert.ok(firstLineFeed >= 0);
  const loneCarriageReturn = `${expected.slice(0, firstLineFeed)}\r${expected.slice(firstLineFeed + 1)}`;
  for (const drifted of [
    `${expected}\nUnexpected drift.\n`,
    expected.slice(0, -20),
    expected.replace('Generated by repo/scripts/generate-setup-question-docs.cjs', 'Altered generated marker'),
    loneCarriageReturn,
  ]) {
    fs.writeFileSync(target, drifted, 'utf8');
    assert.throws(() => generator.checkGeneratedDocument(target), /Stale generated setup question documentation/);
  }

  fs.rmSync(target);
  assert.throws(() => generator.checkGeneratedDocument(target), /Stale generated setup question documentation/);
});

test('setup question writes stay canonical, checkable and idempotent', (t) => {
  const target = temporaryOutput(t);
  const expected = generator.generatedBytes();
  assert.doesNotMatch(expected, /\r\n/);

  generator.writeGeneratedDocument(target);
  const first = fs.readFileSync(target);
  assert.equal(first.toString('utf8'), expected);
  assert.doesNotThrow(() => generator.checkGeneratedDocument(target));

  generator.writeGeneratedDocument(target);
  const second = fs.readFileSync(target);
  assert.deepEqual(second, first);
  assert.doesNotThrow(() => generator.checkGeneratedDocument(target));
});
