'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const n5 = require('../scripts/toolkit-github-governance-review-reconciler.cjs');
const root = path.resolve(__dirname, '..', '..');
const project = path.join(root, 'repo', 'contracts', 'github-governance-review-reconciler');
const generated = path.join(root, 'skills', 'github-governance-review-reconciler');

test('Run-175 RED matrix is closed and has at least thirty cases', () => { const required = ['wrong identity', 'A2', 'duplicate', 'legacy', 'movement', 'byte/order drift', 'body-limit', 'partial', 'uncertain', 'readback', 'review closing', 'open PR inventory', 'merged/closed', 'merged PR inventory', 'pagination', 'material predicates', 'DF not task', 'DF ambiguity', 'frozen promotion', 'executor mutation', 'Codex silence', 'auto-code', 'PR310', 'generated direct edit', 'secret/private', 'idempotent', 'exact digest binding', 'review authority proof', 'A4 review projection', 'source-bound finding provenance', 'typed DF promotion']; assert.equal(n5.RED_FIRST_CASES.length >= 30, true); assert.equal(n5.RED_FIRST_CASES.every((name) => required.some((item) => name.toLowerCase().includes(item.toLowerCase()))), true); });
test('direct contract policy grammar and templates are closed', () => { for (const file of ['github-governance-review-reconciler-contract.schema.json', 'github-governance-review-reconciler-policy.json', 'tracker-v3-grammar.json']) assert.equal(typeof JSON.parse(fs.readFileSync(path.join(project, file), 'utf8')), 'object'); for (const file of ['parent-v3.md', 'child-v3.md', 'pr-v3.md']) { const text = fs.readFileSync(path.join(project, 'templates', file), 'utf8'); assert.match(text, /AI-AGENT-TOOLKIT:N5-(PARENT|CHILD|PR):BEGIN v3/); assert.match(text, /Tracker format contract/); } });
test('direct skill is explicit-only and complete', () => { const output = fs.readFileSync(path.join(generated, 'SKILL.md'), 'utf8'); assert.match(output, /allow_implicit_invocation: false/); assert.match(output, /# N5 GitHub Governance and Truthful PR-Review Reconciler/); assert.ok(fs.existsSync(path.join(generated, 'README.md'))); assert.ok(fs.existsSync(path.join(generated, 'agents', 'openai.yaml'))); });
test('direct contract has no MCP surface', () => { const text = fs.readFileSync(path.join(generated, 'SKILL.md'), 'utf8'); assert.doesNotMatch(text, /MCP spec:/i); });
test('policy makes authority review DF Codex Auto-code and PR310 explicit', () => { const p = JSON.parse(fs.readFileSync(path.join(project, 'github-governance-review-reconciler-policy.json'), 'utf8')); assert.equal(p.authority.a1.sole_mutation_authority, true); assert.equal(p.authority.a3.durable_contract_count, 5); assert.equal(p.review.executor_mutation, false); assert.equal(p.deferred_findings.queue, false); assert.equal(p.codex_review.default, 'enabled'); assert.equal(p.auto_code.mutation, false); assert.equal(p.historical.pr310, 'NO_LONGER_APPLICABLE'); });
test('failure vocabulary and privacy are closed', () => { const p = JSON.parse(fs.readFileSync(path.join(project, 'github-governance-review-reconciler-policy.json'), 'utf8')); for (const code of ['PARENT_BODY_INCOMPLETE', 'PARENT_BYTE_DRIFT', 'PARENT_BODY_LIMIT', 'PARENT_RECONCILIATION_INCOMPLETE', 'N5_CONSENT_REQUIRED', 'N5_REVIEW_INVENTORY_INCOMPLETE', 'N5_DF_AMBIGUOUS', 'N5_REVIEW_MUTATION_DENIED', 'N5_SECRET_OR_PRIVATE_DATA_REJECTED', 'AUTO_CODE_GOVERNANCE_UNREADY']) assert.ok(p.failure_codes.includes(code), code); assert.equal(p.privacy.raw_secrets, false); assert.equal(p.privacy.private_paths, false); });
test('direct skill keeps one shared runtime and no historical cache implementation', () => { const text = fs.readFileSync(path.join(generated, 'SKILL.md'), 'utf8'); assert.match(text, /one\s+shared runtime/i); assert.doesNotMatch(text, /getPairedRecords|caller-token cache implementation/i); });
test('unsupported tracker version is a closed failure', () => { assert.equal(n5.validateTracker({ kind: 'parent', tracker_version: 'v1' }).code, 'N5_TRACKER_VERSION_UNSUPPORTED'); });
