'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const n5 = require('../scripts/toolkit-github-governance-review-reconciler.cjs');
const a1 = require('../scripts/toolkit-control-plane/control-plane-kernel.cjs');

const repository = 'weijunswj/ai-agent-toolkit';
const repositoryId = '1'.repeat(64);
function parentState(overrides = {}) {
  return { kind: 'parent', tracker_version: 'v3', repository, parent_issue: 240,
    current_work: [{ child_id: 'child-1', issue_number: 299, lifecycle: 'current', objective: 'N5 governance', implementation_pr: { number: 0, state: 'not_opened' } }],
    pending_work: [{ child_id: 'child-2', issue_number: 320, lifecycle: 'pending', queue_order: 1, objective: 'Truthful review inventory' }],
    other_open_prs: [], terminal: [], deferred_findings: [], owner_detail: 'Owner bytes remain outside the queue projection.', ...overrides };
}
function childState(overrides = {}) {
  return { kind: 'child', tracker_version: 'v3', repository, issue_number: 299, lifecycle: 'current', objective: 'Govern the canonical parent and direct child topology.',
    progress_checklist: [{ id: 'contract', checked: true, text: 'Accepted contract is preserved.' }],
    scope: { design_lock: 'DL-N5-GITHUB-GOVERNANCE-REVIEW-RECONCILER-001-G2-R1', frozen: true, summary: 'N5 only' }, blockers: [], next_gate: 'Fresh exact-head Web validation', implementation_pr: { number: 0, state: 'not_opened' }, technical_detail: 'Current-state detail only.', ...overrides };
}
function body(kind, state, prefix = 'owner-before\n', suffix = '\nowner-after\n') { return prefix + n5.renderManagedBlock(kind, state) + suffix; }
function enabledA2(canonical_remote = 'https://github.com/weijunswj/ai-agent-toolkit.git') {
  return {
    resolveRepositoryIdentity: () => ({ valid: true, repository_id: repositoryId, canonical_remote }),
    getRepositoryStatus: () => ({ status: 'healthy', actionable: false, repository_id: repositoryId, canonical_remote, capabilities: { 'repository.governance': { state: 'enabled' } } }),
  };
}
function authorisedA1() { return { authorize: ({ operation }) => ({ decision: 'allow', operation_type: operation.type, operation_digest: a1.operationDigest(operation), target_digest: a1.targetDigest(operation) }) }; }
function adapter(initialBody, options = {}) { let current = initialBody; let reads = 0; let writes = 0; const sequence = options.sequence || []; return {
  getParent() { const value = sequence[reads] || { body: current, complete: true, revision: `r${reads}` }; reads += 1; return value; },
  updateParent(payload) { writes += 1; current = payload.body; if (options.updateError) throw new Error('simulated update uncertainty'); return { accepted: true }; },
  reconcileRelated: options.reconcileRelated, get values() { return { current, reads, writes }; }
}; }
function runtime(initialBody, options = {}) { return n5.createRuntime({ repository, authority_broker: options.authority_broker || authorisedA1(), a2: options.a2 || enabledA2(), github: options.github || adapter(initialBody), transaction_owner: options.transaction_owner }); }

test('locked constants and result vocabulary', () => { assert.equal(n5.CONTRACT_VERSION, 'toolkit.n5.github-governance-review-reconciler.v3'); assert.equal(n5.REVIEW_INVENTORY_VERSION, 'toolkit.n5.review-inventory.v1'); assert.deepEqual(n5.INTENTS, ['inspect', 'preview', 'initialise', 'migrate', 'validate', 'reconcile', 'show', 'remove']); assert.equal(n5.MANAGED_MARKERS.parent.begin, '<!-- AI-AGENT-TOOLKIT:N5-PARENT:BEGIN v3 -->'); assert.ok(n5.FAILURE_CODES.includes('PARENT_CONCURRENCY_CONFLICT')); assert.ok(n5.SUCCESS_CODES.includes('N5_RECONCILED')); });
test('render and parse deterministic v3 sections', () => { const state = parentState(); const rendered = n5.renderManagedBlock('parent', state); const parsed = n5.parseManagedBlock(rendered, 'parent', { complete: true }); assert.equal(parsed.ok, true); assert.deepEqual(parsed.state, state); assert.deepEqual(parsed.sections, n5.SECTION_ORDER.parent); assert.match(rendered, /## Current work/); assert.match(rendered, /## Tracker format contract/); });
test('managed replacement preserves unrelated bytes', () => { const original = body('parent', parentState(), 'prefix\n\n', '\n\nsuffix\n'); const result = n5.replaceManagedBlock(original, 'parent', { ...parentState(), owner_detail: 'changed bounded detail' }); assert.equal(result.ok, true); assert.equal(result.prefix, 'prefix\n\n'); assert.equal(result.suffix, '\n\n\nsuffix\n'); assert.equal(result.outside_bytes_preserved, true); assert.match(result.body, /changed bounded detail/); });
test('missing duplicate mismatched and partial managed input fail closed', () => { assert.equal(n5.parseManagedBlock('plain body', 'parent', { complete: true }).code, 'PARENT_PARSE_UNCERTAIN'); const duplicate = body('parent', parentState()) + n5.renderManagedBlock('parent', parentState()); assert.equal(n5.parseManagedBlock(duplicate, 'parent', { complete: true }).code, 'PARENT_PARSE_UNCERTAIN'); assert.equal(n5.parseManagedBlock(n5.renderManagedBlock('child', childState()), 'parent', { complete: true }).code, 'PARENT_PARSE_UNCERTAIN'); assert.equal(n5.parseManagedBlock('', 'parent', { complete: false }).code, 'PARENT_BODY_INCOMPLETE'); });
test('parent queue and lifecycle uniqueness', () => { assert.equal(n5.validateTracker(parentState()).ok, true); assert.equal(n5.validateTracker(parentState({ current_work: [parentState().current_work[0], { ...parentState().current_work[0], child_id: 'child-3', issue_number: 321 }] })).code, 'N5_GOVERNANCE_UNREADY'); assert.equal(n5.validateTracker(parentState({ pending_work: [{ child_id: 'child-2', issue_number: 320, lifecycle: 'pending', queue_order: 2, objective: 'x' }] })).code, 'N5_GOVERNANCE_UNREADY'); assert.equal(n5.validateTracker(parentState({ pending_work: [{ child_id: 'child-2', issue_number: 320, lifecycle: 'pending', queue_order: 1, objective: 'x', queue: 'nested' }] })).code, 'N5_GOVERNANCE_UNREADY'); assert.equal(n5.validateTracker(parentState({ pending_work: [{ child_id: 'child-1', issue_number: 299, lifecycle: 'pending', queue_order: 1, objective: 'duplicate' }] })).code, 'N5_GOVERNANCE_UNREADY'); });
test('failed PR does not complete current child', () => { const state = childState({ implementation_pr: { number: 310, state: 'closed_unmerged' } }); assert.equal(n5.validateTracker(state).ok, true); assert.equal(n5.validateTracker({ ...state, lifecycle: 'terminal' }).code, 'N5_GOVERNANCE_UNREADY'); });
test('read-only intents never mutate', () => { const github = adapter(body('parent', parentState())); const rt = runtime(github.values.current, { github }); assert.equal(rt.inspect({ kind: 'parent', body: github.values.current }).code, 'N5_INSPECTION_READY'); assert.equal(rt.preview({ kind: 'parent', body: github.values.current, update: { type: 'set_field', field: 'owner_detail', value: 'preview' } }).code, 'N5_PREVIEW_READY'); assert.equal(rt.validate({ kind: 'parent', body: github.values.current }).code, 'N5_VALID'); assert.equal(rt.show({ kind: 'parent', body: github.values.current }).code, 'N5_SHOW_READY'); assert.equal(github.values.writes, 0); });
test('mutation requires identity consent preview and A1 authority', () => { const original = body('parent', parentState()); assert.equal(runtime(original).reconcile({ repository: 'other/repo', parent_issue: 240, target: { child_id: 'child-1' }, update: { type: 'set_field', field: 'owner_detail', value: 'x' } }).code, 'N5_REPOSITORY_IDENTITY_MISMATCH'); assert.equal(runtime(original, { a2: { status: () => ({ capabilities: { 'repository.governance': { state: 'unresolved' } } }) } }).reconcile({ repository, parent_issue: 240, target: { child_id: 'child-1' }, update: { type: 'set_field', field: 'owner_detail', value: 'x' }, accepted_preview: true }).code, 'N5_CONSENT_REQUIRED'); assert.equal(runtime(original).reconcile({ repository, parent_issue: 240, target: { child_id: 'child-1' }, update: { type: 'set_field', field: 'owner_detail', value: 'x' } }).code, 'N5_AUTHORITY_REQUIRED'); assert.equal(runtime(original, { authority_broker: { authorize: () => ({ decision: 'allow', operation_type: 'github.read' }) } }).reconcile({ repository, parent_issue: 240, target: { child_id: 'child-1' }, update: { type: 'set_field', field: 'owner_detail', value: 'x' }, accepted_preview: true }).code, 'N5_AUTHORITY_REQUIRED'); });
test('reconcile writes once reads back and reconciles related state', () => { const original = body('parent', parentState()); const github = adapter(original, { reconcileRelated: () => ({ ok: true }) }); const result = runtime(original, { github }).reconcile({ repository, parent_issue: 240, target: { child_id: 'child-1' }, update: { type: 'set_field', field: 'owner_detail', value: 'updated' }, accepted_preview: true }); assert.equal(result.code, 'N5_RECONCILED'); assert.equal(github.values.writes, 1); assert.equal(result.readback.target_state.owner_detail, 'updated'); assert.equal(result.readback.outside_bytes_preserved, true); });
test('reconcile rejects partial missing duplicate and concurrent movement', () => { const original = body('parent', parentState()); assert.equal(runtime(original, { github: adapter(original, { sequence: [{ body: original, complete: false }] }) }).reconcile({ repository, parent_issue: 240, target: { child_id: 'child-1' }, update: { type: 'set_field', field: 'owner_detail', value: 'x' }, accepted_preview: true }).code, 'PARENT_BODY_INCOMPLETE'); assert.equal(runtime(original).reconcile({ repository, parent_issue: 240, target: { child_id: 'missing' }, update: { type: 'set_field', field: 'owner_detail', value: 'x' }, accepted_preview: true }).code, 'PARENT_ENTRY_MISSING'); const duplicateState = parentState({ pending_work: [{ child_id: 'child-1', issue_number: 320, lifecycle: 'pending', queue_order: 1, objective: 'duplicate' }] }); assert.equal(n5.validateTracker(duplicateState).code, 'N5_GOVERNANCE_UNREADY'); const moved = adapter(original, { sequence: [{ body: original, complete: true, revision: 'r0' }, { body: body('parent', { ...parentState(), owner_detail: 'moved' }), complete: true, revision: 'r1' }] }); const result = runtime(original, { github: moved }).reconcile({ repository, parent_issue: 240, target: { child_id: 'child-1' }, update: { type: 'set_field', field: 'owner_detail', value: 'x' }, accepted_preview: true }); assert.equal(result.code, 'PARENT_CONCURRENCY_CONFLICT'); assert.equal(moved.values.writes, 0); });
test('reconcile rejects byte drift and partial cross-resource result', () => { const original = body('parent', parentState()); const drift = adapter(original, { sequence: [{ body: original, complete: true, revision: 'r0' }, { body: original, complete: true, revision: 'r0' }, { body: 'different-owner\n' + n5.renderManagedBlock('parent', { ...parentState(), owner_detail: 'updated' }) + '\nsuffix\n', complete: true, revision: 'r0' }] }); assert.equal(runtime(original, { github: drift }).reconcile({ repository, parent_issue: 240, target: { child_id: 'child-1' }, update: { type: 'set_field', field: 'owner_detail', value: 'updated' }, accepted_preview: true }).code, 'PARENT_BYTE_DRIFT'); const incomplete = adapter(original, { reconcileRelated: () => ({ ok: false }) }); assert.equal(runtime(original, { github: incomplete }).reconcile({ repository, parent_issue: 240, target: { child_id: 'child-1' }, update: { type: 'set_field', field: 'owner_detail', value: 'updated' }, accepted_preview: true }).code, 'PARENT_RECONCILIATION_INCOMPLETE'); });
test('already-correct update is N5_NOOP', () => { const original = body('parent', parentState()); const github = adapter(original); const result = runtime(original, { github }).reconcile({ repository, parent_issue: 240, target: { child_id: 'child-1' }, update: { type: 'set_field', field: 'owner_detail', value: parentState().owner_detail }, accepted_preview: true }); assert.equal(result.code, 'N5_NOOP'); assert.equal(github.values.writes, 0); });
test('body limit is verified-only and compaction preserves live state', () => { assert.equal(n5.classifyBodyLimit('abc', {}).known, false); assert.equal(n5.classifyBodyLimit('abc', { value: 2, unit: 'bytes', provenance: 'verified-transport' }).code, 'PARENT_BODY_LIMIT'); const terminal = { child_id: 'done', issue_number: 1, lifecycle: 'terminal', objective_status: 'disposed', outcome: 'completed', detail: 'x'.repeat(500) }; const state = parentState({ terminal: [terminal] }); assert.equal(n5.compactTerminal(state).code, 'PARENT_BODY_LIMIT'); const proof = { server_authoritative: true, verifiable: true, complete: true, child_issue: 1, disposition: 'disposed', outcome: 'completed', parent_chronology_ref: 'issue/240#run-181', evidence_digest: null }; proof.evidence_digest = n5.durableEvidenceDigest(terminal, proof); const compacted = n5.compactTerminal(state, { durable_evidence: proof }); assert.equal(compacted.ok, true); assert.equal(compacted.state.current_work.length, 1); assert.equal(compacted.state.pending_work.length, 1); assert.ok(compacted.state.terminal[0].detail.length < 500); assert.match(compacted.state.owner_detail, /Owner bytes/); });
test('review inventory separates PRs reviews and conversations', () => { const result = n5.buildReviewInventory({ server_authoritative: true, verifiable: true, pull_requests: [{ number: 1, state: 'open', merged: false, head: 'b'.repeat(40), tree: 'c'.repeat(40), base: 'a'.repeat(40) }, { number: 2, state: 'closed', merged: false }, { number: 3, state: 'merged', merged: true }], submitted_reviews: [{ id: 'review-1', pr_number: 1, state: 'commented' }], inline_conversations: [{ id: 'thread-1', pr_number: 1, resolved: false, outdated: false, closing_reply: false }], pagination: { pull_requests: true, submitted_reviews: true, inline_conversations: true }, current_candidate: { pr_number: 1, head: 'b'.repeat(40), tree: 'c'.repeat(40), base: 'a'.repeat(40) }, require_current_candidate: true, expected_candidate: { pr_number: 1, head: 'b'.repeat(40), tree: 'c'.repeat(40), base: 'a'.repeat(40) } }); assert.equal(result.ok, true); assert.equal(result.review.current, true); assert.equal(result.review.complete, true); assert.equal(result.review.verifiable, true); assert.equal(result.inventory.submitted_reviews.length, 1); assert.equal(result.inventory.inline_conversations.length, 1); assert.equal(result.inventory.pull_requests.length, 3); assert.equal(Object.prototype.hasOwnProperty.call(result, 'findings'), false); });
test('incomplete review pagination is unverifiable', () => { const result = n5.buildReviewInventory({ pull_requests: [], submitted_reviews: [], inline_conversations: [], pagination: { pull_requests: false } }); assert.equal(result.code, 'N5_REVIEW_INVENTORY_INCOMPLETE'); assert.equal(result.review.complete, false); assert.equal(result.review.verifiable, false); });
test('executor review mutation actions are denied', () => { for (const action of ['reply', 'resolve', 'reopen', 'dismiss', 'final_disposition', 'ready', 'merge']) assert.equal(n5.authorizeReviewMutation({ action, actor: 'executor' }).code, 'N5_REVIEW_MUTATION_DENIED'); });
test('finding materiality uses A4 predicates and exclusions', () => { const base = { id: 'finding-1', source_pr: 1, source_thread: 'thread-1', source_candidate: { pr_number: 1, head: 'b'.repeat(40), tree: 'c'.repeat(40), base: 'a'.repeat(40) }, component: 'governance', path: 'repo/scripts/example.cjs', line: 10, text: 'Current candidate failure.', predicates: Object.fromEntries(n5.A4_MATERIAL_PREDICATES.map((key) => [key, true])), exclusions: [] }; assert.equal(n5.classifyFinding(base).finding.materiality, 'material'); assert.equal(n5.classifyFinding({ ...base, exclusions: ['optional'] }).finding.materiality, 'nonblocking'); assert.equal(n5.classifyFinding({ ...base, predicates: { ...base.predicates, material_impact: false } }).finding.materiality, 'nonblocking'); });
test('finding evidence rejects code urls absolute paths and secrets', () => { const base = { id: 'finding-1', provenance: 'G1', pr_number: 1, thread_id: 'thread-1', component: 'boundary', path: 'repo/file.cjs', line: 1, text: 'Safe public evidence', evidence_digest: 'a'.repeat(64), predicates: {} }; assert.equal(n5.classifyFinding({ ...base, text: '```token=secret```' }).code, 'N5_SECRET_OR_PRIVATE_DATA_REJECTED'); assert.equal(n5.classifyFinding({ ...base, text: 'https://example.invalid/private' }).code, 'N5_SECRET_OR_PRIVATE_DATA_REJECTED'); assert.equal(n5.classifyFinding({ ...base, path: 'C:\\Users\\private\\x.cjs' }).code, 'N5_SECRET_OR_PRIVATE_DATA_REJECTED'); });
test('DF is parent-managed and not a queue item', () => { const finding = n5.classifyFinding({ id: 'finding-2', source_pr: 1, source_thread: 'thread-2', source_candidate: { pr_number: 1, head: 'b'.repeat(40), tree: 'c'.repeat(40), base: 'a'.repeat(40) }, component: 'boundary', path: 'repo/file.cjs', line: 2, text: 'Nonblocking public finding', predicates: {} }).finding; const result = n5.registerDeferredFinding({ finding, parent: parentState(), triggers: n5.DF_TRIGGERS }); assert.equal(result.code, 'N5_DF_REGISTERED'); assert.equal(result.parent.deferred_findings.length, 1); assert.equal(result.parent.pending_work.length, 1); assert.equal(result.parent.deferred_findings[0].disposition, 'DEFERRED_REVALIDATE'); assert.equal(result.parent.deferred_findings[0].linked_child, null); assert.deepEqual(result.parent.deferred_findings[0].triggers, n5.DF_TRIGGERS); });
test('DF revalidation truthfully disposes or promotes without widening frozen scope', () => {
  const finding = n5.classifyFinding({ id: 'finding-1', source_pr: 1, source_thread: 'thread-1', source_candidate: { pr_number: 1, head: 'b'.repeat(40), tree: 'c'.repeat(40), base: 'a'.repeat(40) }, component: 'boundary', path: 'repo/file.cjs', line: 2, text: 'Nonblocking public finding', predicates: {} }).finding;
  const registered = n5.registerDeferredFinding({ finding, parent: parentState(), triggers: n5.DF_TRIGGERS });
  assert.equal(registered.code, 'N5_DF_REGISTERED');
  const df = registered.record;
  assert.equal(n5.revalidateDeferredFinding({ record: df, material: false }).record.disposition, 'DISPOSED_NONMATERIAL');
  const existing = n5.revalidateDeferredFinding({ record: df, material: true, compatible_child: { issue_number: 77, direct: true, compatible: true, frozen: false, lifecycle: 'pending' } });
  assert.equal(existing.record.disposition, 'PROMOTED_TO_EXISTING_CHILD');
  assert.equal(existing.record.linked_child, 77);
  assert.equal(n5.revalidateDeferredFinding({ record: df, material: true, compatible_child: { issue_number: 77, direct: true, compatible: true, frozen: true, lifecycle: 'current' } }).code, 'N5_AUTHORITY_REQUIRED');
});
test('Codex silence never persists disabled', () => { assert.equal(n5.codexReviewState({}).state, 'enabled'); assert.equal(n5.codexReviewState({ probe: 'timeout' }).state, 'enabled'); assert.equal(n5.codexReviewState({ owner_disabled: true }).state, 'disabled'); assert.equal(n5.codexReviewState({ owner_disabled: false, probe: 'unavailable_external' }).state, 'enabled'); });
test('Auto-code readiness is read-only', () => { assert.equal(n5.autoCodeReadiness({ governance: 'unresolved' }).code, 'AUTO_CODE_GOVERNANCE_UNREADY'); const result = n5.autoCodeReadiness({ governance: 'enabled', tracker_valid: true, review_inventory_complete: true }); assert.equal(result.code, 'N5_INSPECTION_READY'); assert.equal(result.mutation_attempted, false); });
test('PR310 is no longer applicable only with exact evidence and revival is rejected', () => { const result = n5.adjudicateHistoricalPr310({ historical_closed_unmerged: true, merge_commit: null, current_main_search_complete: true, workflow_inventory_surface_absent: true, caller_token_cache_surface_absent: true, n5_scope_has_no_historical_symbols: true }); assert.equal(result.disposition, 'NO_LONGER_APPLICABLE'); assert.equal(n5.adjudicateHistoricalPr310({ ...result.evidence, current_main_search_complete: false }).code, 'N5_SCOPE_REJECTED'); assert.equal(n5.rejectHistoricalRevival('getPairedRecords').code, 'N5_SCOPE_REJECTED'); });
